/*
    Stop / Start carousel autoplay
*/
$('.btn-customized').on('click', function(){
 
    if( ! $(this).hasClass('disabled') ) {
 
        if( $(this).hasClass('btn-pause') ) {
            $('.carousel').carousel('pause');
        }
        else {
            $('.carousel').carousel('cycle');
        }
 
        $('.btn-pause, .btn-cycle').toggleClass('disabled');
        $(this).blur();
 
    }
 
});